In [1]:
import cv2
import numpy as np

# Load HAAR face classifier
face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load functions
def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Initialize Webcam
cap = cv2.VideoCapture(0)
count = 0

# Collect 100 samples of your face from webcam input
while True:

    ret, frame = cap.read()
    if face_extractor(frame) is not None:
        count += 1
        face = cv2.resize(face_extractor(frame), (200, 200))
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)
        
        # Save file in specified directory with unique name
        file_name_path = 'E:/Faces/sim/' + str(count) + '.jpg'
        cv2.imwrite(file_name_path, face)

        # Put count on images and display live count
        cv2.putText(face, str(count), (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
        cv2.imshow('Face Cropper', face)
        
    else:
        print("Face not found")
        pass

    if cv2.waitKey(1) == ord('q') or count == 100: #13 is the Enter Key
        break
        
cap.release()
cv2.destroyAllWindows()      
print("Collecting Samples Complete")

Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found
Face not found


In [ ]:
cv2.__version__

In [2]:
import cv2
import numpy as np
from os import listdir
from os.path import isfile, join

# Get the training data we previously made
data_path = 'E:/Faces/sim/'
onlyfiles = [f for f in listdir(data_path) if isfile(join(data_path, f))]

# Create arrays for training data and labels
Training_Data, Labels = [], []

# Open training images in our datapath
# Create a numpy array for training data
for i, files in enumerate(onlyfiles):
    image_path = data_path + onlyfiles[i]
    images = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    Training_Data.append(np.asarray(images, dtype=np.uint8))
    Labels.append(i)

# Create a numpy array for both training data and labels
Labels = np.asarray(Labels, dtype=np.int32)

# Initialize facial recognizer
model = cv2.face_LBPHFaceRecognizer.create()

# model=  cv2.face.createLBPHFaceRecognizer()

# Let's train our model 
model.train(np.asarray(Training_Data), np.asarray(Labels))
print("Model trained sucessefully")



Model trained sucessefully


In [3]:
import cv2
import numpy as np


face_classifier = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_detector(img, size=0.5):
    
    # Convert image to grayscale
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_classifier.detectMultiScale(gray, 1.3, 5)
    if faces is ():
        return img, []
    
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        roi = img[y:y+h, x:x+w]
        roi = cv2.resize(roi, (200, 200))
    return img, roi


# Open Webcam
cap = cv2.VideoCapture(0)

while True:

    ret, frame = cap.read()
    
    image, face = face_detector(frame)
    
    try:
        face = cv2.cvtColor(face, cv2.COLOR_BGR2GRAY)

        # Pass face to prediction model
        # "results" comprises of a tuple containing the label and the confidence value
        results = model.predict(face)
        print(results)
        if results[1] < 500:
            confidence = int( 100 * (1 - (results[1])/400) )
            display_string = str(confidence) + '% Confident it is User'
            
        cv2.putText(image, display_string, (100, 120), cv2.FONT_HERSHEY_COMPLEX, 1, (255,120,150), 2)
        
        if confidence > 75:
            cv2.putText(image, "Hey Simran", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
            cv2.imshow('Face Recognition', image )
        else:
            cv2.putText(image, "Locked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
            cv2.imshow('Face Recognition', image )

    except:
        cv2.putText(image, "No Face Found", (220, 120) , cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.putText(image, "Locked", (250, 450), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 2)
        cv2.imshow('Face Recognition', image )
        pass
        
    if cv2.waitKey(1) == ord('q'): #13 is the Enter Key
        break
        
cap.release()
cv2.destroyAllWindows() 









(46, 29.4104713005853)
(46, 30.193510398068877)
(98, 34.419644916459134)
(12, 36.22414813460647)
(98, 30.52069617902339)
(98, 30.12711267124752)
(98, 30.219787744044783)
(98, 29.110966583483517)
(69, 28.911093494715836)
(69, 28.313433504383262)
(69, 28.857265096178903)
(1, 28.98594143403946)
(1, 28.78212457864713)
(5, 30.325345020539622)
(5, 29.748664496782162)
(5, 30.162191808204433)
(81, 30.756025292486008)
(81, 30.28257668049768)
(81, 31.97058603515467)
(81, 31.22113521731944)
(4, 38.965217139173426)
(4, 52.23105047425066)
(92, 54.474749489667886)
(4, 38.52604100161289)
(77, 33.96169048405852)
(80, 32.5566088607316)
(80, 33.85402275353184)
(5, 30.61202838601551)
(1, 31.266096784004773)
(38, 30.668946508094194)
(43, 30.906277556715363)
(43, 30.44097695919402)
(43, 29.94763471234375)
(14, 30.974351765654863)
(1, 30.555627895426237)
(43, 30.780405277817685)
(43, 30.8395540134626)
(1, 31.58632652648909)
(43, 30.80307360544106)
(43, 31.60552496959845)
(40, 31.334297363485778)
(40, 30.934

In [4]:
import cv2,time


In [5]:
video = cv2.VideoCapture(0)
a=1
while True:
    a=a+1
    check,frame=video.read()
    print(frame)
    gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('capturing',gray)
    #key = cv2.waitKey(1)
    if cv2.waitKey(1) == ord('q'):
        break
print(a)
video.release()
cv2.destroyAllWindows()


[[[ 64  75  67]
  [ 72  83  75]
  [ 70  82  77]
  ...
  [174 188 184]
  [173 189 186]
  [176 193 189]]

 [[ 65  77  64]
  [ 71  83  70]
  [ 71  85  74]
  ...
  [174 188 184]
  [175 189 186]
  [176 190 187]]

 [[ 70  82  69]
  [ 68  80  68]
  [ 70  81  71]
  ...
  [174 188 186]
  [171 185 184]
  [172 186 185]]

 ...

 [[ 94  93  98]
  [ 92  91  96]
  [ 99  97 104]
  ...
  [181 185 177]
  [177 181 174]
  [181 185 177]]

 [[ 97  96  98]
  [ 92  91  94]
  [ 93  92  99]
  ...
  [183 187 180]
  [177 182 172]
  [178 183 173]]

 [[113 112 117]
  [106 105 110]
  [ 93  93 104]
  ...
  [182 185 180]
  [175 179 170]
  [176 180 171]]]
[[[ 66  82  74]
  [ 69  84  76]
  [ 71  87  77]
  ...
  [188 191 186]
  [184 190 185]
  [186 191 186]]

 [[ 67  81  73]
  [ 71  84  76]
  [ 69  85  74]
  ...
  [187 192 189]
  [186 191 188]
  [184 190 187]]

 [[ 70  83  75]
  [ 69  82  74]
  [ 66  83  72]
  ...
  [185 192 189]
  [183 191 188]
  [181 189 186]]

 ...

 [[106 108 108]
  [104 106 106]
  [ 92  94  96]
  ..

[[[ 53  70  48]
  [ 51  68  46]
  [ 49  68  46]
  ...
  [158 168 163]
  [158 168 163]
  [162 172 166]]

 [[ 55  71  51]
  [ 53  69  50]
  [ 51  67  47]
  ...
  [160 171 165]
  [163 173 168]
  [163 173 168]]

 [[ 57  70  51]
  [ 58  71  52]
  [ 56  72  52]
  ...
  [164 174 169]
  [165 175 172]
  [164 174 170]]

 ...

 [[ 87  86  91]
  [ 92  91  96]
  [ 88  87  92]
  ...
  [166 169 162]
  [166 169 162]
  [170 174 167]]

 [[ 78  77  82]
  [ 88  87  92]
  [ 92  93  98]
  ...
  [160 165 153]
  [163 165 156]
  [169 171 162]]

 [[ 90  92  94]
  [ 81  82  84]
  [ 98 102 104]
  ...
  [155 160 148]
  [163 165 158]
  [169 170 163]]]
[[[ 49  67  47]
  [ 47  65  45]
  [ 47  69  53]
  ...
  [162 171 168]
  [158 173 169]
  [158 173 169]]

 [[ 49  67  49]
  [ 51  69  51]
  [ 52  71  56]
  ...
  [162 171 168]
  [156 171 167]
  [158 173 169]]

 [[ 49  67  49]
  [ 54  71  54]
  [ 42  64  49]
  ...
  [162 174 170]
  [155 171 170]
  [157 174 172]]

 ...

 [[ 75  82  83]
  [ 81  87  89]
  [ 82  91  93]
  ..

[[[ 40  64  49]
  [ 42  66  50]
  [ 47  69  51]
  ...
  [159 172 168]
  [165 174 175]
  [164 173 174]]

 [[ 39  61  45]
  [ 41  63  47]
  [ 47  66  51]
  ...
  [157 169 168]
  [161 172 173]
  [164 175 176]]

 [[ 39  55  42]
  [ 42  59  46]
  [ 44  61  48]
  ...
  [154 165 164]
  [153 167 165]
  [156 170 169]]

 ...

 [[ 58  64  68]
  [ 65  71  75]
  [ 70  73  82]
  ...
  [159 166 165]
  [158 167 166]
  [160 170 169]]

 [[ 58  63  69]
  [ 62  68  74]
  [ 68  67  81]
  ...
  [155 162 162]
  [157 164 163]
  [158 165 164]]

 [[ 60  65  72]
  [ 59  64  71]
  [ 69  65  81]
  ...
  [154 159 158]
  [155 162 162]
  [159 166 165]]]
[[[ 59  68  49]
  [ 59  68  49]
  [ 56  65  48]
  ...
  [159 172 168]
  [158 170 169]
  [156 168 166]]

 [[ 56  65  46]
  [ 55  64  45]
  [ 54  60  43]
  ...
  [158 173 169]
  [161 175 172]
  [155 169 166]]

 [[ 51  61  44]
  [ 48  59  42]
  [ 50  59  42]
  ...
  [156 174 168]
  [159 176 170]
  [157 175 169]]

 ...

 [[ 73  77  77]
  [ 69  74  73]
  [ 66  71  78]
  ..

[[[ 53  66  51]
  [ 53  66  51]
  [ 51  61  44]
  ...
  [163 169 166]
  [166 173 170]
  [161 169 166]]

 [[ 53  66  51]
  [ 56  68  53]
  [ 52  63  46]
  ...
  [165 172 169]
  [164 174 170]
  [163 173 169]]

 [[ 59  70  53]
  [ 55  66  49]
  [ 53  61  44]
  ...
  [167 175 172]
  [168 176 173]
  [166 173 170]]

 ...

 [[ 55  48 137]
  [ 54  47 136]
  [ 58  51 145]
  ...
  [171 174 172]
  [171 174 172]
  [171 174 172]]

 [[ 47  42 132]
  [ 47  42 132]
  [ 50  42 136]
  ...
  [170 173 170]
  [171 174 172]
  [171 174 172]]

 [[ 47  42 132]
  [ 46  41 130]
  [ 49  41 135]
  ...
  [162 164 164]
  [163 166 164]
  [167 170 167]]]
[[[ 59  60  56]
  [ 58  59  55]
  [ 56  60  53]
  ...
  [156 171 167]
  [148 167 165]
  [148 167 165]]

 [[ 61  62  57]
  [ 62  63  58]
  [ 58  62  55]
  ...
  [157 170 164]
  [157 172 168]
  [157 172 168]]

 [[ 61  62  57]
  [ 62  63  58]
  [ 58  62  57]
  ...
  [151 164 156]
  [148 166 159]
  [153 170 164]]

 ...

 [[ 45  44 126]
  [ 45  44 126]
  [ 45  45 124]
  ..

[[[ 68  77  58]
  [ 60  69  50]
  [ 63  67  49]
  ...
  [162 166 159]
  [159 164 150]
  [159 164 150]]

 [[ 65  75  58]
  [ 60  71  54]
  [ 63  69  53]
  ...
  [159 167 162]
  [155 163 151]
  [160 167 155]]

 [[ 66  74  57]
  [ 66  74  57]
  [ 62  71  54]
  ...
  [157 167 162]
  [151 160 150]
  [161 170 160]]

 ...

 [[ 93  95  97]
  [ 86  88  90]
  [ 77  79  81]
  ...
  [163 166 165]
  [167 169 169]
  [168 170 170]]

 [[ 85  86  91]
  [ 78  79  84]
  [ 74  75  79]
  ...
  [169 169 169]
  [167 169 169]
  [168 170 170]]

 [[ 80  79  84]
  [ 79  78  83]
  [ 77  76  80]
  ...
  [166 166 166]
  [163 163 163]
  [165 165 165]]]
[[[ 53  67  59]
  [ 58  71  63]
  [ 63  73  66]
  ...
  [167 174 173]
  [163 173 169]
  [159 169 166]]

 [[ 53  67  59]
  [ 59  73  64]
  [ 63  73  66]
  ...
  [166 173 170]
  [163 173 169]
  [159 169 166]]

 [[ 54  65  57]
  [ 57  68  60]
  [ 58  69  61]
  ...
  [166 173 170]
  [165 172 169]
  [161 169 166]]

 ...

 [[ 82  83  86]
  [ 82  83  86]
  [ 80  83  87]
  ..

[[[ 53  67  57]
  [ 51  65  55]
  [ 49  62  54]
  ...
  [153 176 167]
  [156 178 169]
  [149 171 162]]

 [[ 54  65  57]
  [ 56  66  59]
  [ 56  66  60]
  ...
  [153 176 167]
  [154 176 170]
  [151 173 166]]

 [[ 52  62  57]
  [ 57  67  62]
  [ 59  69  64]
  ...
  [157 176 170]
  [155 175 169]
  [154 174 168]]

 ...

 [[ 81  84  90]
  [ 80  83  89]
  [ 80  82  91]
  ...
  [163 166 164]
  [164 167 165]
  [169 172 169]]

 [[ 81  81  90]
  [ 78  78  87]
  [ 78  81  90]
  ...
  [164 165 162]
  [164 165 162]
  [169 169 167]]

 [[ 76  79  87]
  [ 75  77  86]
  [ 76  79  87]
  ...
  [162 162 160]
  [163 164 161]
  [169 169 167]]]
[[[ 55  62  50]
  [ 59  66  54]
  [ 56  67  57]
  ...
  [149 169 169]
  [146 167 167]
  [149 169 169]]

 [[ 56  64  52]
  [ 61  68  56]
  [ 55  68  58]
  ...
  [150 170 171]
  [149 169 169]
  [150 170 171]]

 [[ 60  67  55]
  [ 60  67  55]
  [ 53  67  57]
  ...
  [145 165 168]
  [147 167 170]
  [150 170 172]]

 ...

 [[ 68  74  80]
  [ 73  78  85]
  [ 76  81  90]
  ..

[[[ 49  66  40]
  [ 55  72  45]
  [ 50  67  43]
  ...
  [165 175 170]
  [165 175 170]
  [160 171 165]]

 [[ 49  65  43]
  [ 52  69  47]
  [ 50  66  44]
  ...
  [164 174 169]
  [164 174 169]
  [163 173 168]]

 [[ 53  67  46]
  [ 52  66  44]
  [ 51  68  46]
  ...
  [164 172 166]
  [164 172 166]
  [164 172 166]]

 ...

 [[ 82  85  92]
  [ 80  83  89]
  [ 80  82  91]
  ...
  [176 176 176]
  [175 175 175]
  [171 171 171]]

 [[ 81  84  90]
  [ 77  80  87]
  [ 78  81  90]
  ...
  [177 177 177]
  [172 172 172]
  [172 172 172]]

 [[ 75  77  86]
  [ 73  75  84]
  [ 78  81  90]
  ...
  [166 166 166]
  [163 163 163]
  [169 169 169]]]
[[[ 75  68  57]
  [ 70  63  53]
  [ 76  72  61]
  ...
  [157 173 165]
  [152 170 161]
  [152 170 161]]

 [[ 71  64  56]
  [ 74  66  58]
  [ 72  70  59]
  ...
  [154 171 167]
  [158 173 169]
  [158 173 169]]

 [[ 65  60  51]
  [ 70  66  57]
  [ 72  67  58]
  ...
  [157 172 168]
  [160 174 170]
  [158 173 169]]

 ...

 [[ 73  78  86]
  [ 75  80  89]
  [ 82  84  93]
  ..

[[[118 118 116]
  [127 127 125]
  [116 120 120]
  ...
  [168 178 177]
  [171 180 179]
  [171 180 179]]

 [[119 120 115]
  [125 126 121]
  [112 117 115]
  ...
  [166 175 175]
  [170 182 180]
  [169 180 179]]

 [[126 127 122]
  [123 124 120]
  [117 119 117]
  ...
  [159 171 170]
  [165 179 178]
  [165 179 178]]

 ...

 [[ 61  68  69]
  [ 58  64  66]
  [ 54  58  60]
  ...
  [ 47  49 133]
  [ 46  47 132]
  [ 43  44 128]]

 [[ 62  66  70]
  [ 60  63  68]
  [ 57  59  61]
  ...
  [ 45  49 131]
  [ 45  46 130]
  [ 42  43 127]]

 [[ 62  65  72]
  [ 60  63  69]
  [ 56  57  62]
  ...
  [ 43  47 129]
  [ 30  31 115]
  [ 32  33 118]]]
[[[128 134 131]
  [119 124 122]
  [118 122 124]
  ...
  [168 180 176]
  [168 180 176]
  [169 181 177]]

 [[134 137 133]
  [124 127 122]
  [117 121 123]
  ...
  [172 182 177]
  [170 179 176]
  [168 178 175]]

 [[135 140 130]
  [121 126 116]
  [117 123 117]
  ...
  [171 181 177]
  [168 178 175]
  [167 177 174]]

 ...

 [[ 69  72  69]
  [ 63  66  63]
  [ 54  57  54]
  ..

[[[127 129 110]
  [152 154 136]
  [141 147 121]
  ...
  [202 207 195]
  [207 211 204]
  [207 211 204]]

 [[126 129 113]
  [141 145 128]
  [142 147 126]
  ...
  [207 209 200]
  [205 209 202]
  [203 207 199]]

 [[137 141 127]
  [140 143 129]
  [141 145 127]
  ...
  [205 209 202]
  [204 210 203]
  [203 209 202]]

 ...

 [[124 117 116]
  [130 123 122]
  [ 80  77  70]
  ...
  [ 41  46 145]
  [ 41  46 143]
  [ 47  52 149]]

 [[108 106 104]
  [114 112 110]
  [ 77  75  73]
  ...
  [ 41  46 145]
  [ 42  44 144]
  [ 41  43 143]]

 [[115 116 113]
  [120 120 118]
  [ 80  80  80]
  ...
  [ 40  44 144]
  [ 43  45 145]
  [ 41  43 143]]]
[[[112 118 113]
  [109 114 109]
  [102 115 109]
  ...
  [201 206 203]
  [203 208 205]
  [198 204 201]]

 [[113 117 112]
  [112 115 110]
  [107 117 112]
  ...
  [199 205 200]
  [199 205 202]
  [199 205 202]]

 [[115 116 112]
  [114 115 110]
  [111 117 112]
  ...
  [202 207 204]
  [196 201 198]
  [196 201 198]]

 ...

 [[106 108 101]
  [125 126 119]
  [123 125 118]
  ..

[[[172 176 150]
  [177 180 155]
  [187 185 163]
  ...
  [212 224 211]
  [219 229 222]
  [220 231 223]]

 [[177 180 157]
  [179 182 159]
  [183 184 161]
  ...
  [216 226 213]
  [218 227 217]
  [221 230 220]]

 [[182 182 162]
  [182 182 162]
  [182 182 162]
  ...
  [219 229 217]
  [217 227 215]
  [216 226 213]]

 ...

 [[147 146 148]
  [152 152 154]
  [155 156 151]
  ...
  [ 85  73 174]
  [ 82  72 173]
  [ 78  69 170]]

 [[149 146 148]
  [156 153 155]
  [146 147 140]
  ...
  [ 93  82 181]
  [ 81  75 171]
  [ 69  63 159]]

 [[148 145 147]
  [156 153 155]
  [139 139 132]
  ...
  [100  89 186]
  [ 81  74 173]
  [ 61  54 153]]]
[[[172 176 150]
  [177 180 155]
  [187 185 163]
  ...
  [212 224 211]
  [219 229 222]
  [220 231 223]]

 [[177 180 157]
  [179 182 159]
  [183 184 161]
  ...
  [216 226 213]
  [218 227 217]
  [221 230 220]]

 [[182 182 162]
  [182 182 162]
  [182 182 162]
  ...
  [219 229 217]
  [217 227 215]
  [216 226 213]]

 ...

 [[147 146 148]
  [152 152 154]
  [155 156 151]
  ..

[[[183 181 172]
  [185 182 173]
  [182 181 167]
  ...
  [225 230 216]
  [221 227 213]
  [221 227 213]]

 [[185 182 173]
  [186 183 174]
  [181 182 169]
  ...
  [223 228 214]
  [220 226 212]
  [221 227 213]]

 [[186 184 173]
  [186 184 173]
  [183 183 170]
  ...
  [225 230 216]
  [221 226 215]
  [223 228 216]]

 ...

 [[155 146 147]
  [164 155 156]
  [161 158 152]
  ...
  [104  93 189]
  [ 81  75 169]
  [ 66  60 154]]

 [[157 150 150]
  [155 148 149]
  [154 151 145]
  ...
  [ 99  91 187]
  [ 84  78 174]
  [ 66  60 156]]

 [[163 157 155]
  [158 151 150]
  [158 155 148]
  ...
  [ 89  80 177]
  [ 74  68 164]
  [ 69  63 159]]]
[[[170 166 155]
  [170 166 155]
  [173 168 159]
  ...
  [216 225 217]
  [215 223 216]
  [218 227 219]]

 [[171 169 157]
  [170 168 156]
  [170 167 158]
  ...
  [216 225 215]
  [216 225 217]
  [217 226 218]]

 [[175 173 162]
  [174 172 161]
  [174 172 163]
  ...
  [218 227 217]
  [216 225 215]
  [216 225 215]]

 ...

 [[128 122 125]
  [143 138 140]
  [144 144 144]
  ..

[[[181 179 168]
  [179 177 166]
  [186 186 175]
  ...
  [214 226 213]
  [213 224 214]
  [220 231 221]]

 [[179 176 167]
  [177 174 165]
  [185 183 171]
  ...
  [215 224 212]
  [215 224 214]
  [218 227 217]]

 [[175 173 164]
  [171 168 159]
  [174 172 161]
  ...
  [214 223 213]
  [215 224 214]
  [217 226 216]]

 ...

 [[132 132 132]
  [132 132 132]
  [129 129 129]
  ...
  [ 62  63 151]
  [ 62  62 155]
  [ 64  63 156]]

 [[127 127 127]
  [134 134 134]
  [132 132 132]
  ...
  [ 59  61 152]
  [ 59  61 154]
  [ 60  62 155]]

 [[122 122 122]
  [129 129 129]
  [131 133 133]
  ...
  [ 55  57 147]
  [ 51  52 147]
  [ 49  50 145]]]
[[[181 179 168]
  [179 177 166]
  [186 186 175]
  ...
  [214 226 213]
  [213 224 214]
  [220 231 221]]

 [[179 176 167]
  [177 174 165]
  [185 183 171]
  ...
  [215 224 212]
  [215 224 214]
  [218 227 217]]

 [[175 173 164]
  [171 168 159]
  [174 172 161]
  ...
  [214 223 213]
  [215 224 214]
  [217 226 216]]

 ...

 [[132 132 132]
  [132 132 132]
  [129 129 129]
  ..

[[[171 174 162]
  [170 173 161]
  [170 173 159]
  ...
  [202 211 203]
  [206 214 206]
  [208 216 209]]

 [[171 174 162]
  [170 173 161]
  [171 174 160]
  ...
  [206 214 206]
  [207 215 208]
  [208 216 209]]

 [[170 173 161]
  [170 173 161]
  [172 175 162]
  ...
  [209 218 210]
  [207 215 208]
  [207 215 208]]

 ...

 [[114 111 123]
  [115 113 124]
  [116 114 124]
  ...
  [100 113 144]
  [104 115 146]
  [104 115 146]]

 [[110 109 121]
  [118 117 129]
  [116 114 125]
  ...
  [101 114 147]
  [103 116 149]
  [ 99 112 144]]

 [[114 113 127]
  [122 122 135]
  [121 118 130]
  ...
  [ 93 106 139]
  [ 97 110 143]
  [ 90 103 136]]]
[[[180 177 161]
  [182 179 163]
  [183 180 164]
  ...
  [211 218 206]
  [210 217 205]
  [210 217 205]]

 [[180 176 163]
  [182 178 165]
  [183 180 164]
  ...
  [211 218 206]
  [214 219 208]
  [213 218 206]]

 [[180 176 163]
  [182 178 165]
  [183 179 166]
  ...
  [211 216 204]
  [214 219 208]
  [214 219 208]]

 ...

 [[123 121 121]
  [132 130 130]
  [129 129 129]
  ..

[[[174 177 156]
  [177 179 158]
  [176 181 160]
  ...
  [213 217 212]
  [211 214 209]
  [216 219 214]]

 [[172 173 157]
  [174 176 160]
  [176 177 159]
  ...
  [216 219 214]
  [213 217 212]
  [216 219 214]]

 [[169 169 156]
  [171 172 158]
  [176 177 161]
  ...
  [217 220 215]
  [213 217 212]
  [214 218 213]]

 ...

 [[123 122 127]
  [125 123 128]
  [123 119 126]
  ...
  [ 63  64 159]
  [ 66  67 164]
  [ 65  65 163]]

 [[126 125 129]
  [128 127 132]
  [115 114 121]
  ...
  [ 61  64 159]
  [ 65  65 163]
  [ 64  64 162]]

 [[127 126 130]
  [121 120 125]
  [ 89  86  91]
  ...
  [ 63  66 163]
  [ 60  60 160]
  [ 58  58 158]]]
[[[173 174 162]
  [177 177 166]
  [172 172 161]
  ...
  [208 215 214]
  [211 219 216]
  [208 215 212]]

 [[174 175 163]
  [176 176 164]
  [173 174 162]
  ...
  [209 216 215]
  [209 217 214]
  [209 217 214]]

 [[174 174 165]
  [173 173 164]
  [171 171 162]
  ...
  [208 215 212]
  [206 216 212]
  [207 217 214]]

 ...

 [[117 116 128]
  [120 120 131]
  [121 121 131]
  ..

[[[170 170 147]
  [175 176 153]
  [177 175 157]
  ...
  [212 217 207]
  [212 217 207]
  [217 221 212]]

 [[178 177 161]
  [178 177 161]
  [180 177 161]
  ...
  [212 217 207]
  [211 218 208]
  [212 219 209]]

 [[173 172 158]
  [178 176 163]
  [179 177 164]
  ...
  [211 218 208]
  [210 217 207]
  [211 218 208]]

 ...

 [[121 116 126]
  [122 118 127]
  [121 117 124]
  ...
  [ 35  38 122]
  [ 39  41 123]
  [ 39  41 123]]

 [[125 122 132]
  [125 122 132]
  [126 122 129]
  ...
  [ 39  44 125]
  [ 37  39 120]
  [ 33  35 117]]

 [[130 128 138]
  [129 127 136]
  [127 123 128]
  ...
  [ 53  55 137]
  [ 34  33 118]
  [ 31  30 114]]]
[[[177 177 175]
  [176 176 174]
  [179 180 176]
  ...
  [205 209 202]
  [211 214 209]
  [212 215 211]]

 [[176 177 172]
  [176 177 172]
  [177 178 173]
  ...
  [210 214 206]
  [210 213 208]
  [211 214 209]]

 [[173 175 168]
  [171 173 166]
  [170 172 165]
  ...
  [212 216 209]
  [209 213 205]
  [209 213 205]]

 ...

 [[113 112 117]
  [120 119 123]
  [119 118 121]
  ..